### ISSUE TITLE
Future plans and fixes

### ISSUE THREAD

**Issue by TheNamlessGuy** [TheNamlessGuy/browser-tab-grouper#1]
# TODO

- [ ] Make the group tab interface friendlier
- [ ] Better highlight what tabs belong to what group
- [ ] "Keep tabs opened from within the group in the group" option

# Done

**Comment by Skrad** [comment]
I love the "Keep tabs opened from within the group in the group" option. 
The interface is friendly thanks.

**Comment by TheNamlessGuy** [comment]
> I accidentally missed these plans when posting feature requests or I'd have just commented here.

No problem, better to break them out into separate issues if there's some discussion needed.

**Comment by TheNamlessGuy** [comment]
Note to myself: Use [cookies.getAllCookieStores](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/getAllCookieStores) and see what value a non-contextual-identity-tab returns.

**Comment by DavidScottWorks** [comment]
Is there a way to auto-color the tabs which belong to a group when you open the group? Maybe a way to keep the checkbox 'checked'

**Comment by TheNamlessGuy** [comment]
> Is there a way to auto-color the tabs which belong to a group when you open the group?

Not at the moment, from what I can tell. See the task regarding contextual identities above, and the discussion [here](https://github.com/TheNamlessGuy/browser-tab-grouper/issues/5)

> Maybe a way to keep the checkbox 'checked'

I'm not sure what you mean

**Comment by DavidScottWorks** [comment]
I think you've done great work with this. I'll try to explain what I mean better

> > Maybe a way to keep the checkbox 'checked'
> 
> I'm not sure what you mean

The 'Highlight tabs in group' Action. Instead of needing to click that action every time to highlight the tabs perhaps change it to an always on or off 'checkbox' like is in the Options section. That way anytime you open the group the tabs can be automatically highlighted. I'm not even sure that's possible given the limitations

**Comment by TheNamlessGuy** [comment]
> The 'Highlight tabs in group' Action. Instead of needing to click that action every time to highlight the tabs perhaps change it to an always on or off 'checkbox' like is in the Options section. That way anytime you open the group the tabs can be automatically highlighted. I'm not even sure that's possible given the limitations

Ah, I see what you mean. You sadly can't make it permanent, as it just "selects" the tabs. You can replicate this behavior by clicking on one tab, holding down shift, and clicking on another tab. For that reason, it will automatically un-select all tabs as soon as you click on something.
You could re-select them anytime they're unselected, but that would be a nightmare if you wanted to move tabs around at all.

I could probably add an option to auto-'Highlight tabs in group' when you open the group though, if that's helpful?

**Comment by asclepiadae** [comment]
Just wanted to jump in here with a tiny bit of further research I did down a rabbit-hole of colouring tabs (initial thought was can we use the theme API). Seems this was an issue for a legacy extension ColorfulTabs (among others), and there was some discussion on [their forum](https://www.addongenie.com/forums/topic/colorfultabs-disabled-in-firefox-quantum) about limitations at the time of the Quantum/WebExtension switch.

Long-story short, it seems like there _is_ a [Bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1320585) related to this feature request, which had some early participation from Mozilla devs and core contributors, but which is now sitting open and seemingly abandoned as there was a fundamental disagreement whether this capability belonged in the extensions or theme API (plus the people who pushed against lifting customization restrictions to streamline the user experience). 

Not sure this actually helps much at the end of the day - unless that API request gets back to being an active consideration, it appears there's no way to customize the UI per tab.

**Comment by TheNamlessGuy** [comment]
> Long-story short, it seems like there _is_ a [Bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1320585) related to this feature request, which had some early participation from Mozilla devs and core contributors, but which is now sitting open and seemingly abandoned as there was a fundamental disagreement whether this capability belonged in the extensions or theme API (plus the people who pushed against lifting customization restrictions to streamline the user experience).
> 
> Not sure this actually helps much at the end of the day - unless that API request gets back to being an active consideration, it appears there's no way to customize the UI per tab.

It does seem like this isn't a priority feature for firefox, which I suppose is understandable.

> Edit to add: It looks like there is some work on tab groups in Nightly builds: https://connect.mozilla.org/t5/ideas/native-tab-grouping-more-customizable-tab-bar/idc-p/76640/highlight/true#M41296 However, I'm unsure if this is actually an API-based changed or a core component feature. Might be worth looking into as well.

From what I've seen on the nightly build, the feature is a one-to-one replication of the chromium tab grouping feature, which would make this plugin obsolete once it finally reaches the production branch.

**Comment by Unsafewater** [comment]
Hey, thanks for the work on this extension, i have been using it quite a lot. There is one issue and one suggestion i have. 

The issue is that the group doesn't expand when you have a group and a tab outside of it and close that tab, automatically switching you to the group tab. It's worse when you just have a group and a tab and nothing else, because the only work-around to get the group to auto expand is by opening another tab outside the group and switching to the group and then closing that tab. 

Secondly, the suggestion would be something along the lines of a toggle in the group tab settings changing the specific group to auto hide or not, if it is possible. I use this extension (and previously chrome tabs) for organizing material for different courses and it is incredibly helpful for that purpose. But sometimes i just need a quick search on a new tab and the group autohiding is a bit inconvenient. 

Again, thanks for the work on this extension and i understand if you cease developing it, due to it being a feature that is being actively officially implemented.

**Comment by TheNamlessGuy** [comment]
> The issue is that the group doesn't expand when you have a group and a tab outside of it and close that tab, automatically switching you to the group tab. It's worse when you just have a group and a tab and nothing else, because the only work-around to get the group to auto expand is by opening another tab outside the group and switching to the group and then closing that tab.

Have you encountered this issue with plugin version 0.3.1 or later? It should be fixed in that version (see [this issue](https://github.com/TheNamlessGuy/browser-tab-grouper/issues/8))

> Secondly, the suggestion would be something along the lines of a toggle in the group tab settings changing the specific group to auto hide or not, if it is possible. I use this extension (and previously chrome tabs) for organizing material for different courses and it is incredibly helpful for that purpose. But sometimes i just need a quick search on a new tab and the group autohiding is a bit inconvenient.

I suppose I could, but considering the fact that there's no way to discern what groups are tabbed and which are not, I don't think it would be that helpful.  
If it's behind a toggle you might be able to chalk it up to "you've only got yourself to blame though"... I'll take a look.

> Again, thanks for the work on this extension and i understand if you cease developing it, due to it being a feature that is being actively officially implemented.

We'll see how well the official one works for my use-cases. The listing in the group tab itself has become a must for me, for example.

**Comment by Unsafewater** [comment]
> > The issue is that the group doesn't expand when you have a group and a tab outside of it and close that tab, automatically switching you to the group tab. It's worse when you just have a group and a tab and nothing else, because the only work-around to get the group to auto expand is by opening another tab outside the group and switching to the group and then closing that tab.
> 
> Have you encountered this issue with plugin version 0.3.1 or later? It should be fixed in that version (see [this issue](https://github.com/TheNamlessGuy/browser-tab-grouper/issues/8))
> 
> > Secondly, the suggestion would be something along the lines of a toggle in the group tab settings changing the specific group to auto hide or not, if it is possible. I use this extension (and previously chrome tabs) for organizing material for different courses and it is incredibly helpful for that purpose. But sometimes i just need a quick search on a new tab and the group autohiding is a bit inconvenient.
> 
> I suppose I could, but considering the fact that there's no way to discern what groups are tabbed and which are not, I don't think it would be that helpful. If it's behind a toggle you might be able to chalk it up to "you've only got yourself to blame though"... I'll take a look.
> 
> > Again, thanks for the work on this extension and i understand if you cease developing it, due to it being a feature that is being actively officially implemented.
> 
> We'll see how well the official one works for my use-cases. The listing in the group tab itself has become a must for me, for example.

Sorry for responding so late, i hadn't thought to check this sooner, my bad. I also apologize if i don't sound very coherent, english isn't my first language and a lot of what i'll be describing could probably be solved by changing how i do things, especially a more reasonable tab management. I'll definitely try to do better there.

I can confirm that i have not had the issue with the group not expanding the last few times i closed out of a tab that took me to the group. I also had a slightly older version of FF installed which could also be one of the causes but everything is updated and solved now, sorry for that. 

In regards to the tabs not auto-collapsing, i believe it's a very useful thing because i maintain way too many tabs open at times. And i usually keep my groups together. So, if today i'm studying course 1, i'd want to toggle all the others to collapse except course 1, this way i have all the pdfs and other material for course 1 open and easily accessible. And if i open a new tab to do some random 10 second search it won't auto-collapse. This may sound dumb, but if there was a secondary toggle to make it so the tabs didn't auto-show as well it would be even better. As in a "manual control" toggle and a button to hide the group tabs, and another button to show the group tabs.

I'm mostly using an older laptop (2016) with 16 GB RAM for university work, that has stayed in the lab, and at times i have felt some performance issues. Mostly when reading papers to make reports/presentations or things like that. That sometimes means i have literally 20+ tabs with stuff for that specific work and often whole book pdfs opened on firefox, since it's what i use as a pdf viewer. I believe these performance issues happened due not having firefox restarted for a few days while not fully shutting down the computer, just suspending it. With these performance issues, the tabs un-hide at like 2-3 tabs a second, which is quite annoying. Especially if i clicked out of the group accidentally. This performance when un-hiding, also happens when hiding the tabs. 

Speaking of the performance, i have triggered another weird behavior of the extension that i believe is a bug or just an extremely niche edge case. I'm not certain why it happens only sometimes, but basically if the tabs are hiding and un-hiding slowly, it can sometimes get stuck in a loop when you change from one group to another. G1 = group 1, G2 = group 2.

You select G1, it starts slowly showing the tabs one by one, then select G2 before G1 is done showing all tabs. 
This will cause G1 to finish showing all the tabs before re-hiding them, while G2 is also showing the tabs one by one. 
When G1 finishes showing the tabs, it switches you to the last tab you were on within G1, taking you out of G2 and I guess introducing a hide G2 instruction into the queue. 
This makes G1 start showing the tabs one by one again, or atleast loading that instruction into a queue for when it finishes hiding. If G2 is still working on showing it's tabs, when it finishes showing them it'll switch you the last G2 tab you were on, taking you out of G1 and triggering the loop.

Sorry for the quite long text, i tried to keep it simple while explaining both the new problem and why i believe the toggle for auto-hiding would be useful, but i clearly failed. I'll also check back here sooner, if you need any clarification on the issue.

**Comment by TheNamlessGuy** [comment]
> Sorry for responding so late, i hadn't thought to check this sooner, my bad. I also apologize if i don't sound very coherent, english isn't my first language and a lot of what i'll be describing could probably be solved by changing how i do things, especially a more reasonable tab management. I'll definitely try to do better there.

No need to apologize, While I'm making this plugin mostly for my own benefit, I do try to keep up with as many different workflows as I reasonably can manage.

> I can confirm that i have not had the issue with the group not expanding the last few times i closed out of a tab that took me to the group. I also had a slightly older version of FF installed which could also be one of the causes but everything is updated and solved now, sorry for that.

No problem, better one report too many than one too few.

> In regards to the tabs not auto-collapsing, i believe it's a very useful thing because i maintain way too many tabs open at times. And i usually keep my groups together. So, if today i'm studying course 1, i'd want to toggle all the others to collapse except course 1, this way i have all the pdfs and other material for course 1 open and easily accessible. And if i open a new tab to do some random 10 second search it won't auto-collapse. This may sound dumb, but if there was a secondary toggle to make it so the tabs didn't auto-show as well it would be even better. As in a "manual control" toggle and a button to hide the group tabs, and another button to show the group tabs.
> 
> I'm mostly using an older laptop (2016) with 16 GB RAM for university work, that has stayed in the lab, and at times i have felt some performance issues. Mostly when reading papers to make reports/presentations or things like that. That sometimes means i have literally 20+ tabs with stuff for that specific work and often whole book pdfs opened on firefox, since it's what i use as a pdf viewer. I believe these performance issues happened due not having firefox restarted for a few days while not fully shutting down the computer, just suspending it. With these performance issues, the tabs un-hide at like 2-3 tabs a second, which is quite annoying. Especially if i clicked out of the group accidentally. This performance when un-hiding, also happens when hiding the tabs.

I moved this issue [over here](https://github.com/TheNamlessGuy/browser-tab-grouper/issues/11).

> Speaking of the performance, i have triggered another weird behavior of the extension that i believe is a bug or just an extremely niche edge case. I'm not certain why it happens only sometimes, but basically if the tabs are hiding and un-hiding slowly, it can sometimes get stuck in a loop when you change from one group to another. G1 = group 1, G2 = group 2.
> 
> You select G1, it starts slowly showing the tabs one by one, then select G2 before G1 is done showing all tabs. This will cause G1 to finish showing all the tabs before re-hiding them, while G2 is also showing the tabs one by one. When G1 finishes showing the tabs, it switches you to the last tab you were on within G1, taking you out of G2 and I guess introducing a hide G2 instruction into the queue. This makes G1 start showing the tabs one by one again, or atleast loading that instruction into a queue for when it finishes hiding. If G2 is still working on showing it's tabs, when it finishes showing them it'll switch you the last G2 tab you were on, taking you out of G1 and triggering the loop.

Not sure what I can really do about this, but I'll give it a try. Moved to [here](https://github.com/TheNamlessGuy/browser-tab-grouper/issues/12).

> Sorry for the quite long text, i tried to keep it simple while explaining both the new problem and why i believe the toggle for auto-hiding would be useful, but i clearly failed. I'll also check back here sooner, if you need any clarification on the issue.

Again, no problem. I'm just glad people find a use for the dumb plugin I made for myself.

**Comment by TheNamlessGuy** [comment]
@Unsafewater The collapse toggle should be fixed in 0.5.0 (out whenever Firefox says its OK). I couldn't find a good solution for the swapping issue, but I'll keep the issue open, and I'll take a look another time.

**Comment by HellPhantom** [comment]
Much better than the new build in tabs grouping. Excellent plugin can't live without it.

Please add option to be able to saver Options settings to persist as a default settings. So all new groups use the default saved Options. I have to always modify the options for a new group to how I like them.

Again Excellent Plugin.

**Comment by TheNamlessGuy** [comment]
> Please add option to be able to saver Options settings to persist as a default settings

That would mean that the plugin needs to start using storage, which I'm not really a fan of. I guess I could make it optional and opt-in just for this, though.
